- name: Stop AMQP Proxy.
  shell:
    cmd: systemctl stop amqproxy
    chdir: /tmp/amqproxy

- name: Add an Apt signing key
  apt_key:
    url: https://keybase.io/crystal/pgp_keys.asc
    state: present

- apt_repository:
    repo: deb https://dist.crystal-lang.org/apt crystal main
    state: present

- name: "Install AMQP Proxy Packages"
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - libssl-dev
    - libxml2-dev
    - libyaml-dev
    - libgmp-dev
    - libreadline-dev
    - libz-dev
    - crystal
    - help2man
    - lintian
    - policykit-1

- name: Remove Preinstalled Git AMQP Proxy
  run_once: yes
  become: true
  command: "{{item}}"
  with_items:
    - "rm -rf /tmp/amqproxy"

- name: Clone a private repository into /tmp/amqproxy.
  git:
    repo: https://github.com/cloudamqp/amqproxy.git
    version: master
    dest: /tmp/amqproxy
    accept_hostkey: yes
    update: yes

- name: Install AMQP Proxy.
  shell:
    cmd: shards build --release --production
    chdir: /tmp/amqproxy

- name: Copy Binary to /usr/bin
  shell:
    cmd: cp bin/amqproxy /usr/bin
    chdir: /tmp/amqproxy

- name: delete amqproxy.service
  file:
    path: "/etc/systemd/system/amqproxy.service"
    state: absent

- name: render amqproxy.service
  template: src=amqproxy.service.j2 dest=/etc/systemd/system/amqproxy.service

- name: enable amqproxy service
  shell:
    cmd: systemctl enable amqproxy
    chdir: /

- name: start amqproxy service
  shell:
    cmd: systemctl start amqproxy
    chdir: /